d /etc/notation - - - -
d /etc/notation/plugins - - - -
d /var/cache/notation - - - -
d /etc/notation/truststore - - - -
d /etc/notation/truststore/x509 - - - -
d /etc/notation/truststore/x509/signingAuthority - - - -
