schema-version = 2
# pointing to my private kit
release-version = "14.5.0-cis"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.74.0"
vendor = "bottlerocket"
