[package]
name = "binutils"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
url = "https://mirrors.kernel.org/gnu/binutils/binutils-2.39.tar.xz"
sha512 = "68e038f339a8c21faa19a57bbc447a51c817f47c2e06d740847c6e9cc3396c025d35d5369fa8c3f8b70414757c89f0e577939ddc0d70f283182504920f53b0a3"

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
